# Generated by Django 6.1.1 on 2026-09-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('QUOTATION', 'Quotation'), ('INVOICE', 'Invoice')], max_length=20, unique=True)),
                ('prefix', models.CharField(default='QTN', max_length=20)),
                ('starting_number', models.PositiveIntegerField(default=1)),
                ('number_of_digits', models.PositiveIntegerField(default=4)),
                ('format_pattern', models.CharField(default='{prefix}-{number}', help_text='Use {prefix}, {number}, and optional {year} placeholders (e.g. {prefix}-{number} or ASC/{prefix}/{year}/{number})', max_length=100)),
                ('current_sequence', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
