# Generated by Django 6.1.1 on 2026-09-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Default GST / Tax %', max_digits=5)),
                ('unit', models.CharField(default='unit', help_text='e.g. piece, hour, month, day', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
