# Generated by Django 6.1.1 on 2026-09-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='My Business Inc.', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=255)),
                ('gst_number', models.CharField(blank=True, default='', help_text='GSTIN / Tax ID', max_length=50)),
                ('pan_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', max_length=100)),
                ('account_details', models.TextField(blank=True, default='', help_text='Account Name, Number, IFSC / SWIFT / IBAN')),
                ('payment_information', models.TextField(blank=True, default='', help_text='UPI ID, PayPal, wire instructions')),
                ('default_terms', models.TextField(blank=True, default='1. Payment is due within 15 days of invoice date.\n2. Please include invoice number on your payment.\n3. Goods/services once delivered cannot be returned without prior agreement.')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='company_signatures/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
